### PR TITLE
ENH: Add `itk_image_to_multiscale` method

### PR DESCRIPTION
**Pull request by tbirdso**
Adds helper method for directly converting an `itk.Image` object to a
`MultiscaleSpatialImage`. Includes 2D and 3D tests and updates ITK
conversion example.

Includes workaround for `itk.xarray_from_image` reference counting issue
resolved in
[https://github.com/InsightSoftwareConsortium/ITK/pull/3438](https://github.com/InsightSoftwareConsortium/ITK/pull/3438) to be included in itk>v5.3rc04 packages.

Resolves [https://github.com/spatial-image/multiscale-spatial-image/issues/44](https://github.com/spatial-image/multiscale-spatial-image/issues/44).

### CODE REVIEW

**Review by thewtex — DISMISSED** [review]
@tbirdso absolutely awesome!! :100: :1st_place_medal: 

One item -- can we please continue to use the xarray/matplotlib methods in the notebook example to demonstrate best practices and the value of MultiscaleSpatialImage. This display:

- Accounts for anisotropic spacing correctly in the spatial metadata
- Displays the correct values along the axis in physical space
- Displays the anatomical orientation

For an interactive, 3D view of the data, we will soon have itkwidgets, which will also display this information :-)

**Comment by thewtex** [comment]
CC @PaulHax @bnmajor @lydiang

**Comment by tbirdso** [comment]
@thewtex Sure thing, I have reverted the notebook to rely on xarray/matplotlib visuals

**Comment by thewtex** [comment]
@tbirdso thanks!

**Pull request merged**
