### PR TITLE
raise error for invalid scale factors

### PR DESCRIPTION
**Pull request by giovp**
cross ref from here https://github.com/scverse/spatialdata/issues/110

@thewtex  here a `ValueError` is raised but please let me know if you think a logging or just a warning should be raised instead.

I tried to make dask fail with invalid chunk sizes as described here: https://github.com/scverse/spatialdata/issues/110#issuecomment-1399616374 I *think* I understood what you mean but I didn't manage to make a reprex with couple of resizing methods (`Methods.XARRAY_COARSEN` and `Methods.DASK_IMAGE_NEAREST`). Basically even if I pass larger-than-axes chunks the method would still bound to the max value for that dimension, I'll try a bit more later. On a separate note, should this check happen at *inferred* chunk sizes from the passed `chunks` and 1image.shape` or should it happen after the resizing already completed (before returning the DataTree). Thank you!

### CODE REVIEW

**Review by thewtex — APPROVED** [review]
:100:

**Comment by thewtex** [comment]
@giovp thank you for the contribution! :clap: 

Overall looks good, CI is failing due handling of the dimensions (it may help to use the dict identifier for dimensions).

Thanks for taking a look at the chunk size issue. Yes, we can look at the chunk size issue as a follow-up. It may be at reduced scales that the chunk sizes need to be reduced to be at most the shape of the reduced array (I think this could be done during multiscale generation automatically when required).

**Comment by giovp** [comment]
@thewtex I believe the test now fails cause time `t` is also included in the check against scale factors, with error:

```
FAILED test/test_ngff_validation.py::test_t_z_y_x_c_valid_ngff - ValueError: Scale factor 4 is incompatible with image shape (2, 32, 32, 16, 3) along dimension t.
```
is this desirable or shall I exclude `t` the same way channels `c` are excluded?

**Review by thewtex — APPROVED** [review]
:100:

**Pull request merged**
