### PR TITLE
ENH: And Convert Tiff File with OME-NGFF Zarr output

### PR DESCRIPTION
**Pull request by thewtex**
@joshmoore tried to create a bioformats2raw transitional layout. Does this look correct? Can your package validate it?

### CODE REVIEW

**Comment by joshmoore** [comment]
This block:
```
store = zarr.storage.DirectoryStore(f'{image_name}.zarr', dimension_separator='/')
group = zarr.group(store, overwrite=True)
group.attrs['bioformats2raw.layout'] = 3
store['OME/METADATA.ome.xml'] = tiff.ome_metadata.encode('utf-8')
```
certainly looks correct. Is there one of these Zarrs somewhere that I can try to validate?

**Comment by thewtex** [comment]
@joshmoore yes, here it is: https://drive.google.com/file/d/1LaTE1yjCI4fJbLQS84tuGUwD5OyQRRy6/view?usp=sharing

**Comment by joshmoore** [comment]
From Python :+1:
```
ome_zarr info sub-I46_ses-SPIM_sample-BrocaAreaS01_stain-GAD67_chunk-00_SPIM.zarr/
/Users/jamoore/Downloads/sub-I46_ses-SPIM_sample-BrocaAreaS01_stain-GAD67_chunk-00_SPIM.zarr [zgroup]
 - metadata
   - bioformats2raw
 - data
/Users/jamoore/Downloads/sub-I46_ses-SPIM_sample-BrocaAreaS01_stain-GAD67_chunk-00_SPIM.zarr/0 [zgroup]
 - metadata
   - Multiscales
 - data
   - (242, 342, 3882)
   - (242, 342, 1941)
   - (121, 171, 485)
   - (30, 42, 60)
```

**Comment by joshmoore** [comment]
ZarrReader.java was less happy: https://github.com/ome/ZarrReader/pull/31#issuecomment-1119303509 but that may be because of orthogonal advances.

**Comment by thewtex** [comment]
@djarecka @yarikoptic @satra please take a look

**Pull request merged**
